baseURL = "https://jacmoe.github.io/brandt/"
languageCode = "en-us"
title = "Brandt's Duployan"
publishDir = "docs"
theme = "hugo-theme-relearn"
canonifyURLs = true
relativeURLs = true

[outputs]
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]

[params]
  author = "Jacob Moena"
  description = "This site is dedicated to Brandt's Duployan shorthand adaptation to English. It provides information, manual, PDFs, Anki decks, and other resources."
  themeVariant = [ "zen-light", "zen-dark" ]
  disableExplicitIndexURLs = true
  externalLinkTarget = "_blank"
  alwaysopen = false

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
url = "https://github.com/jacmoe/brandt"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-reddit'></i> Shorthand Community"
url = "https://www.reddit.com/r/shorthand/"
weight = 20

[markup.goldmark.renderer]
unsafe = true
